version: "3"

services:
  db:
    image: postgres
    environment:
      POSTGRES_PASSWORD: postgres
      POSTGRES_USER: postgres
      POSTGRES_DB: postgres
    ports:
      - "5432:5432"
    volumes:
      - postgres-data:/var/lib/postgresql/data
    networks:
      - db

  backend:
    image: backend
    container_name: backend
    build:
      context: ./backend
      dockerfile: Dockerfile
    expose:
      - 443
      - 80
    depends_on:
      - db
    environment:
      - ConnectionStrings__DatabaseConnection=Server=db;Port=5432;Database=postgres;Username=postgres;Password=postgres
    networks:
      - reverse_proxy
      - db
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.back.rule=Host(`api.$DOMAIN_NAME`)"
      - "traefik.http.services.back.loadbalancer.server.port=80"
      - "traefik.http.routers.back.entrypoints=websecure"
      - "traefik.http.routers.back.tls.certresolver=mvallew"

  frontend:
    image: frontend
    container_name: frontend
    build:
      context: ./frontend
      dockerfile: Dockerfile
    depends_on:
      - backend
    environment:
      - REACT_APP_API_URL=https://backend
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.front.rule=Host(`$DOMAIN_NAME`)"
      - "traefik.http.services.front.loadbalancer.server.port=80"
      - "traefik.http.routers.front.entrypoints=websecure"
      - "traefik.http.routers.front.tls.certresolver=mvallew"
    networks:
      - reverse_proxy

volumes:
  postgres-data:

networks:
  db:
  reverse_proxy:
    name: traefik
    external: true